### PR TITLE
Fix(conversion): consistent interface for invalid GTINs

### LINKED ISSUE #5: Consistent interface for invalid GTIN objects
In an oversight with PR #3, when methods were added to convert between _valid_ GTINs like `to_gtin_8` etc. and `to_all_valid`, the `BarcodeValidation::InvalidGTIN` object was not updated with the same interface.

This results in errors when trying to convert an _invalid_ GTIN into other formats:

```ruby
> BarcodeValidation.scan("123456").to_all_valid
NoMethodError: undefined method `to_all_valid' for #<BarcodeValidation::InvalidGTIN input="123456" error="nil">
```

When attempting to convert a valid GTIN into an invalid format, it currently returns a `BarcodeValidation::InvalidGTIN`.

This behaviour should be consistent when attempting to convert an _invalid_ GTIN into _any_ format; it should simply return itself.

When calling `to_all_valid` on an _invalid_ GTIN, it should return an empty array.

### PR DESCRIPTION
**Pull request by beet**
Attempting to convert an invalid GTIN into other formats should return an invalid GTIN object instead of raising a NoMethodError exception.

Resolves #5

### CODE REVIEW

File: spec/lib/barcodevalidation_spec.rb [hunk 1]
```diff
@@ -104,5 +104,41 @@
         expect(realtime / valid_inputs.count).to be < 0.000_05 # 50us
       end
     end
+
+    describe "conversion" do
+      context "for an invalid barcode" do
+        let(:input) { "123456" }
+
+        context "#to_all_valid" do
+          it "is a an empty array" do
```
Comment (kaitlinw) [inline spec/lib/barcodevalidation_spec.rb]: 👀 ok very picky little grammar bit here!

**Review by kaitlinw — APPROVED** [review]
just the little grammar bit :D and its good!

**Comment by ellsclytn** [comment]
Just an FYI: You've got `Resolves issue #5` in your commit. GitHub won't auto-close #5 though, because it needs to just be `Resolves #5`

**Comment by beet** [comment]
> Just an FYI: You've got `Resolves issue #5` in your commit. GitHub won't auto-close #5 though, because it needs to just be `Resolves #5`

Thanks, rebase to the rescue!
